os: linux
dist: bionic
compiler: gcc-8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
language: cpp
notifications: never
before_install: bash ./scripts/before_install.sh
jobs:
  include:
    - stage: "Build and Test"
      script: bash ./scripts/build_and_run_tests.sh
      name: "Unit Tests"
    - script: bash ./scripts/run_code_coverage.sh
      name: "Code Coverage"
    - script: mkdir docs && bash ./scripts/run_doxygen.sh
      name: "Documentation Generation"
      deploy:
        provider: pages
        token: $GH_TOKEN
        skip_cleanup: true
        local_dir: ./docs/html